export const WOMEN_SEED_DATA = [
  { name: '武则天', name_en: 'Wu Zetian', wiki_title: 'Wu_Zetian' },
  { name: '李清照', name_en: 'Li Qingzhao', wiki_title: 'Li_Qingzhao' },
  { name: '秋瑾', name_en: 'Qiu Jin', wiki_title: 'Qiu_Jin' },
  { name: '林徽因', name_en: 'Lin Huiyin', wiki_title: 'Lin_Huiyin' },
  { name: '张爱玲', name_en: 'Eileen Chang', wiki_title: 'Eileen_Chang' },
  { name: '花木兰', name_en: 'Hua Mulan', wiki_title: 'Hua_Mulan' },
  { name: '丁玲', name_en: 'Ding Ling', wiki_title: 'Ding_Ling' },
  { name: '冰心', name_en: 'Bing Xin', wiki_title: 'Bing_Xin' },
  { name: '屠呦呦', name_en: 'Tu Youyou', wiki_title: 'Tu_Youyou' },
  { name: '班昭', name_en: 'Ban Zhao', wiki_title: 'Ban_Zhao' },
  { name: '上官婉儿', name_en: 'Shangguan Waner', wiki_title: 'Shangguan_Wan%27er' },
  { name: '蔡文姬', name_en: 'Cai Wenji', wiki_title: 'Cai_Yan' },
  { name: '王昭君', name_en: 'Wang Zhaojun', wiki_title: 'Wang_Zhaojun' },
  { name: '宋庆龄', name_en: 'Soong Ching-ling', wiki_title: 'Soong_Ching-ling' },
  { name: '邓颖超', name_en: 'Deng Yingchao', wiki_title: 'Deng_Yingchao' },
  { name: '谢冰心', name_en: 'Xie Bingxin', wiki_title: 'Bing_Xin' },
  { name: '郎平', name_en: 'Lang Ping', wiki_title: 'Lang_Ping' },
  { name: '邓亚萍', name_en: 'Deng Yaping', wiki_title: 'Deng_Yaping' },
  { name: '董明珠', name_en: 'Dong Mingzhu', wiki_title: 'Dong_Mingzhu' },
  { name: '张桂梅', name_en: 'Zhang Guimei', wiki_title: 'Zhang_Guimei' },
  { name: '柳青', name_en: 'Jean Liu', wiki_title: 'Jean_Liu' },
  { name: '谷爱凌', name_en: 'Eileen Gu', wiki_title: 'Eileen_Gu' },
  { name: '杨澜', name_en: 'Yang Lan', wiki_title: 'Yang_Lan' },
  { name: '梅艳芳', name_en: 'Anita Mui', wiki_title: 'Anita_Mui' },
  { name: '张曼玉', name_en: 'Maggie Cheung', wiki_title: 'Maggie_Cheung' },
  { name: '与谢野晶子', name_en: 'Yosano Akiko', wiki_title: 'Yosano_Akiko' },
  { name: '樋口一叶', name_en: 'Ichiyo Higuchi', wiki_title: 'Ichiy%C5%8D_Higuchi' },
  { name: '申师任堂', name_en: 'Shin Saimdang', wiki_title: 'Shin_Saimdang' },
  { name: '大坂直美', name_en: 'Naomi Osaka', wiki_title: 'Naomi_Osaka' },
  { name: '英迪拉·甘地', name_en: 'Indira Gandhi', wiki_title: 'Indira_Gandhi' },
  { name: '贝娜齐尔·布托', name_en: 'Benazir Bhutto', wiki_title: 'Benazir_Bhutto' },
  { name: '马拉拉', name_en: 'Malala Yousafzai', wiki_title: 'Malala_Yousafzai' },
  { name: '克利奥帕特拉', name_en: 'Cleopatra', wiki_title: 'Cleopatra' },
  { name: '旺加里·马塔伊', name_en: 'Wangari Maathai', wiki_title: 'Wangari_Maathai' },
  { name: '奇玛曼达·阿迪契', name_en: 'Chimamanda Ngozi Adichie', wiki_title: 'Chimamanda_Ngozi_Adichie' },
  { name: '希帕蒂娅', name_en: 'Hypatia', wiki_title: 'Hypatia' },
  { name: '萨福', name_en: 'Sappho', wiki_title: 'Sappho' },
  { name: '圣女贞德', name_en: 'Joan of Arc', wiki_title: 'Joan_of_Arc' },
  { name: '伊丽莎白一世', name_en: 'Elizabeth I', wiki_title: 'Elizabeth_I' },
  { name: '叶卡捷琳娜大帝', name_en: 'Catherine the Great', wiki_title: 'Catherine_the_Great' },
  { name: '居里夫人', name_en: 'Marie Curie', wiki_title: 'Marie_Curie' },
  { name: '南丁格尔', name_en: 'Florence Nightingale', wiki_title: 'Florence_Nightingale' },
  { name: '弗里达·卡罗', name_en: 'Frida Kahlo', wiki_title: 'Frida_Kahlo' },
  { name: '弗吉尼亚·伍尔夫', name_en: 'Virginia Woolf', wiki_title: 'Virginia_Woolf' },
  { name: '艾达·洛芙莱斯', name_en: 'Ada Lovelace', wiki_title: 'Ada_Lovelace' },
  { name: '西蒙娜·德·波伏瓦', name_en: 'Simone de Beauvoir', wiki_title: 'Simone_de_Beauvoir' },
  { name: '可可·香奈儿', name_en: 'Coco Chanel', wiki_title: 'Coco_Chanel' },
  { name: '罗莎琳·富兰克林', name_en: 'Rosalind Franklin', wiki_title: 'Rosalind_Franklin' },
  { name: '艾米·诺特', name_en: 'Emmy Noether', wiki_title: 'Emmy_Noether' },
  { name: '海蒂·拉玛', name_en: 'Hedy Lamarr', wiki_title: 'Hedy_Lamarr' },
  { name: '哈丽雅特·塔布曼', name_en: 'Harriet Tubman', wiki_title: 'Harriet_Tubman' },
  { name: '罗莎·帕克斯', name_en: 'Rosa Parks', wiki_title: 'Rosa_Parks' },
  { name: '阿梅莉亚·埃尔哈特', name_en: 'Amelia Earhart', wiki_title: 'Amelia_Earhart' },
  { name: '埃莉诺·罗斯福', name_en: 'Eleanor Roosevelt', wiki_title: 'Eleanor_Roosevelt' },
  { name: '玛雅·安吉罗', name_en: 'Maya Angelou', wiki_title: 'Maya_Angelou' },
  { name: '奥普拉·温弗瑞', name_en: 'Oprah Winfrey', wiki_title: 'Oprah_Winfrey' },
  { name: '玛格丽特·撒切尔', name_en: 'Margaret Thatcher', wiki_title: 'Margaret_Thatcher' },
  { name: '安格拉·默克尔', name_en: 'Angela Merkel', wiki_title: 'Angela_Merkel' },
  { name: '米歇尔·奥巴马', name_en: 'Michelle Obama', wiki_title: 'Michelle_Obama' },
  { name: '格蕾塔·通贝里', name_en: 'Greta Thunberg', wiki_title: 'Greta_Thunberg' },
  { name: '玛丽·雪莱', name_en: 'Mary Shelley', wiki_title: 'Mary_Shelley' },
  { name: '简·奥斯汀', name_en: 'Jane Austen', wiki_title: 'Jane_Austen' },
  { name: '托妮·莫里森', name_en: 'Toni Morrison', wiki_title: 'Toni_Morrison' },
  { name: '贝琳达·布朗', name_en: 'Brene Brown', wiki_title: 'Bren%C3%A9_Brown' },
  { name: '惠特尼·沃尔夫·赫德', name_en: 'Whitney Wolfe Herd', wiki_title: 'Whitney_Wolfe_Herd' },
  { name: '莎拉·布蕾克利', name_en: 'Sara Blakely', wiki_title: 'Sara_Blakely' },
  { name: '雪莉·桑德伯格', name_en: 'Sheryl Sandberg', wiki_title: 'Sheryl_Sandberg' },
  { name: '阿里安娜·赫芬顿', name_en: 'Arianna Huffington', wiki_title: 'Arianna_Huffington' },
  { name: '克里斯蒂娜·拉加德', name_en: 'Christine Lagarde', wiki_title: 'Christine_Lagarde' },
  { name: '瑞诗玛·索贾尼', name_en: 'Reshma Saujani', wiki_title: 'Reshma_Saujani' },
  { name: '碧昂丝', name_en: 'Beyonce', wiki_title: 'Beyonc%C3%A9' },
  { name: '泰勒·斯威夫特', name_en: 'Taylor Swift', wiki_title: 'Taylor_Swift' },
  { name: '嘎嘎小姐', name_en: 'Lady Gaga', wiki_title: 'Lady_Gaga' },
  { name: '塞雷娜·威廉姆斯', name_en: 'Serena Williams', wiki_title: 'Serena_Williams' },
  { name: '西蒙·拜尔斯', name_en: 'Simone Biles', wiki_title: 'Simone_Biles' },
  { name: '薇奥拉·戴维斯', name_en: 'Viola Davis', wiki_title: 'Viola_Davis' },
  { name: '艾玛·沃森', name_en: 'Emma Watson', wiki_title: 'Emma_Watson' },
  { name: '敏迪·卡灵', name_en: 'Mindy Kaling', wiki_title: 'Mindy_Kaling' },
  { name: '蒂娜·特纳', name_en: 'Tina Turner', wiki_title: 'Tina_Turner' },
  { name: '戴安娜王妃', name_en: 'Diana, Princess of Wales', wiki_title: 'Diana,_Princess_of_Wales' },
  { name: 'J.K. 罗琳', name_en: 'J. K. Rowling', wiki_title: 'J._K._Rowling' },
  { name: '维奥拉·德斯蒙德', name_en: 'Viola Desmond', wiki_title: 'Viola_Desmond' },
  { name: '里戈韦塔·门楚', name_en: 'Rigoberta Menchu', wiki_title: 'Rigoberta_Mench%C3%BA' },
  { name: '胡安娜修女', name_en: 'Juana Ines de la Cruz', wiki_title: 'Juana_In%C3%A9s_de_la_Cruz' },
  { name: '瓦里斯·迪里', name_en: 'Waris Dirie', wiki_title: 'Waris_Dirie' },
  { name: '特蕾莎修女', name_en: 'Mother Teresa', wiki_title: 'Mother_Teresa' },
  { name: '珍·古道尔', name_en: 'Jane Goodall', wiki_title: 'Jane_Goodall' },
  { name: '伊蕾娜·约里奥-居里', name_en: 'Irene Joliot-Curie', wiki_title: 'Ir%C3%A8ne_Joliot-Curie' },
  { name: '纳迪亚·穆拉德', name_en: 'Nadia Murad', wiki_title: 'Nadia_Murad' },
  { name: '露丝·弗斯特', name_en: 'Ruth First', wiki_title: 'Ruth_First' },
  { name: '瓦伦蒂娜·捷列什科娃', name_en: 'Valentina Tereshkova', wiki_title: 'Valentina_Tereshkova' },
  { name: '萨福·佩凯', name_en: 'Toor Pekai Yousafzai', wiki_title: 'Toor_Pekai_Yousafzai' },
  { name: '阿马尔·克鲁尼', name_en: 'Amal Clooney', wiki_title: 'Amal_Clooney' },
  { name: '奥黛丽·赫本', name_en: 'Audrey Hepburn', wiki_title: 'Audrey_Hepburn' },
  { name: '海伦·凯勒', name_en: 'Helen Keller', wiki_title: 'Helen_Keller' },
  { name: '玛格丽特·米德', name_en: 'Margaret Mead', wiki_title: 'Margaret_Mead' },
  { name: '雷切尔·卡森', name_en: 'Rachel Carson', wiki_title: 'Rachel_Carson' },
  { name: '卡玛拉·哈里斯', name_en: 'Kamala Harris', wiki_title: 'Kamala_Harris' },
  { name: '杰辛达·阿德恩', name_en: 'Jacinda Ardern', wiki_title: 'Jacinda_Ardern' },
  { name: '玛格丽特·汉密尔顿', name_en: 'Margaret Hamilton', wiki_title: 'Margaret_Hamilton_(software_engineer)' },
];
